language: objective-c

branches:
 only:
 - master

xcode_workspace: TravisTest.xcworkspace
xcode_scheme: TravisTest
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2

script:
- xcodebuild -workspace TravisTest.xcworkspace -list
# - xcodebuild clean build test -workspace TravisTest.xcworkspace -scheme TravisTest clean -configuration Debug BUILD_ACTIVE_ARCH=NO -destination 'platform=iphonesimulator,name=iPhone 6'
