language: objective-c

branches:
 only:
 - master

xcode_workspace: TravisTest.xcworkspace
xcode_scheme: TravisTestTests
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2

script:
- xcodebuild clean build test -workspace TravisTest.xcworkspace -scheme TravisTest
